services:
  asm:
    image: asm-template
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - ./projects:/home/ubuntu/projects
    stdin_open: true # docker run -i
    tty: true        # docker run -t
